### ISSUE TITLE
zsnap property KeyError: 'creation'

### ISSUE THREAD

**Issue by ecoop3r** [Rudd-O/zfs-tools#14]
root@stor2:~# zsnap -k 24 -p auto-hourly- dpool
Traceback (most recent call last):
  File "/usr/local/bin/zsnap", line 5, in <module>
    pkg_resources.run_script('zfs-tools==0.4.1', 'zsnap')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/zfs_tools-0.4.1-py2.7.egg/EGG-INFO/scripts/zsnap", line 82, in <module>
    ssn = sorted([ (x.get_property('creation'), x.name, x) for x in source_dataset.get_snapshots(flt) ])
  File "/usr/local/lib/python2.7/dist-packages/zfs_tools-0.4.1-py2.7.egg/zfstools/models.py", line 95, in get_property
    return self._properties[name]
KeyError: 'creation'

I'm looking into this issue it appears that the parse_zfs_r_output function in models.py isn't populating the creations property.  Reverting to commit 56b56fe486eeb28179ac8040501f94f6fa7c1f9f resolves the problem for the time being.

**Comment by Rudd-O** [comment]
Fixed

**Comment by ecoop3r** [comment]
Thanks Rudd-O works great.  You the man.

**Comment by Rudd-O** [comment]
No prob.  Happy to help :-)
